<?php
/**
 * Blog post og:tags
 *
 * @var \Magefan\Blog\Block\Post\View\Opengraph $block
 * @var \Magento\Framework\Escaper $escaper
 * @var \Web200\Seo\ViewModel\OpenGraph $viewModel
 */

$viewModel = $block->getData('view_model');
if (!isset($escaper)) {
    /* Compatability fix for old Magento versions */
    $escaper = $block;
}
?>

<meta property="og:type" content="<?= $escaper->escapeHtml($block->getType()); ?>" />
<meta property="og:title" content="<?= $escaper->escapeHtml($block->getTitle()); ?>" />
<meta property="og:description" content="<?= $escaper->escapeHtml($block->getDescription()); ?>" />
<meta property="og:url" content="<?= $escaper->escapeHtml($block->getPageUrl()); ?>" />
<?php if ($image = $block->getImage()) { ?>
    <meta property="og:image" content="<?= $escaper->escapeHtml($image); ?>" />
<?php } ?>
<meta property="og:locale" content="<?= $block->escapeHtml($viewModel->getOgLocale()) ?>" />